apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-db-app
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: pricelist
  source:
    path: pricelist/database
    repoURL: https://github.com/luigiaparicio/gitops-examples
    targetRevision: master
  syncPolicy: {}
