apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    route:
      enabled: true
  dex:
    openShiftOAuth: true
    image: quay.io/redhat-cop/dex
    version: v2.22.0-openshift
  resourceCustomizations: |
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /spec/host
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      g, admins, role:admin
      g, developer, role:developer
      g, marketing, role:marketing
    scopes: '[groups]'
  initialRepositories: |
    - name: cluster-config
      type: git
      url: https://github.com/luigiaparicio/openshift-cluster-config
    - name: examples
      type: git
      url: https://github.com/luigiaparicio/gitops-examples
    - name: right-lyrics
      type: git
      url: https://github.com/luigiaparicio/right-lyrics
